# Generated by Django 2.0.8 on 2018-09-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=255)),
                ('par_1', models.CharField(blank=True, max_length=255)),
                ('par_2', models.CharField(blank=True, max_length=255)),
                ('par_3', models.CharField(blank=True, max_length=255)),
                ('score_results', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
