# Generated by Django 2.1.4 on 2019-01-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('doc_name', models.CharField(blank=True, max_length=255)),
                ('doc_type', models.CharField(blank=True, max_length=255)),
                ('digitalized_by', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ScoreResults',
        ),
    ]
